final drivers = [
  {'avatar': null, 'id': 1, 'name': '演示网盘1', 'type': 'alipan'},
  {'avatar': null, 'id': 2, 'name': '演示网盘2', 'type': 'webdav'},
  {'avatar': null, 'id': 3, 'name': '演示网盘3', 'type': 'quark'},
];
final servers = [
  {'active': true, 'host': 'Internal Server', 'id': 0, 'type': 'local', 'invalid': false},
];
final fileList = [
  {
    'category': null,
    'contentHash': null,
    'createdAt': '+002023-05-07T10:37:46.921000000Z',
    'id': '',
    'name': 'Folder 1',
    'parentId': 'root',
    'size': null,
    'type': 'folder',
    'updatedAt': '+002024-11-04T08:49:29.308000000Z',
    'url': null,
  },
  {
    'category': null,
    'contentHash': null,
    'createdAt': '+002024-01-27T08:45:25.834000000Z',
    'id': '',
    'name': 'Folder 2',
    'parentId': 'root',
    'size': null,
    'type': 'folder',
    'updatedAt': '+002024-01-27T08:45:25.834000000Z',
    'url': null,
  },
  {
    'category': null,
    'contentHash': null,
    'createdAt': '+002023-05-20T09:32:13.392000000Z',
    'id': '',
    'name': 'Folder 3',
    'parentId': 'root',
    'size': null,
    'type': 'folder',
    'updatedAt': '+002023-05-20T09:32:13.392000000Z',
    'url': null,
  },
  {
    'category': 'audio',
    'contentHash': null,
    'createdAt': '+002023-07-28T05:22:40.666000000Z',
    'id': '',
    'name': 'File 1.mp3',
    'parentId': 'root',
    'size': null,
    'type': 'file',
    'updatedAt': '+002023-07-28T05:22:40.666000000Z',
    'url': null,
  },
  {
    'category': 'video',
    'contentHash': null,
    'createdAt': '+002023-05-07T10:37:28.735000000Z',
    'id': '',
    'name': 'File 2.mp4',
    'parentId': 'root',
    'size': null,
    'type': 'file',
    'updatedAt': '+002024-11-13T06:57:15.609000000Z',
    'url': null,
  },
];

final playlists = [
  {'id': 3, 'title': 'DEFAULT', 'url': ''},
];
final channels = [
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV1.png',
    'links': [''],
    'title': 'CCTV-1',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV2.png',
    'links': [''],
    'title': 'CCTV-2',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV3.png',
    'links': [''],
    'title': 'CCTV-3',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV4.png',
    'links': [''],
    'title': 'CCTV-4',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV5.png',
    'links': [''],
    'title': 'CCTV-5',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV5+.png',
    'links': [''],
    'title': 'CCTV-5+',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV6.png',
    'links': [''],
    'title': 'CCTV-6',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV7.png',
    'links': [''],
    'title': 'CCTV-7',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV8.png',
    'links': [''],
    'title': 'CCTV-8',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV9.png',
    'links': [''],
    'title': 'CCTV-9',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV10.png',
    'links': [''],
    'title': 'CCTV-10',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV11.png',
    'links': [''],
    'title': 'CCTV-11',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV12.png',
    'links': [''],
    'title': 'CCTV-12',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV13.png',
    'links': [''],
    'title': 'CCTV-13',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV14.png',
    'links': [''],
    'title': 'CCTV-14',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV15.png',
    'links': [''],
    'title': 'CCTV-15',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV16.png',
    'links': [''],
    'title': 'CCTV-16',
  },
  {
    'id': 0,
    'category': '📺央视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV17.png',
    'links': [''],
    'title': 'CCTV-17',
  },
  {
    'id': 0,
    'category': '📡卫视频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/广东卫视.png',
    'links': [''],
    'title': '广东卫视',
  },
  {
    'id': 0,
    'category': '☘️广东频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/广东珠江.png',
    'links': [''],
    'title': '广东珠江',
  },
  {
    'id': 0,
    'category': '☘️浙江频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/浙江钱江.png',
    'links': [''],
    'title': '浙江钱江',
  },
  {
    'id': 0,
    'category': '☘️北京频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/北京科教.png',
    'links': [''],
    'title': '北京科教',
  },
  {
    'id': 0,
    'category': '☘️上海频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/七彩戏剧.png',
    'links': [''],
    'title': '七彩戏剧',
  },
  {
    'id': 0,
    'category': '☘️重庆频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/万源新闻综合.png',
    'links': [''],
    'title': '万源新闻综合',
  },
  {
    'id': 0,
    'category': '☘️江苏频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/六合新闻综合.png',
    'links': [''],
    'title': '六合新闻综合',
  },
  {
    'id': 0,
    'category': '☘️湖南频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/湖南都市.png',
    'links': [''],
    'title': '湖南都市',
  },
  {
    'id': 0,
    'category': '☘️湖北频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/湖北影视.png',
    'links': [''],
    'title': '湖北影视',
  },
  {
    'id': 0,
    'category': '☘️广西频道',
    'image': 'https://gh.catmak.name/https://raw.githubusercontent.com/fanmingming/live/main/tv/南宁公共.png',
    'links': [''],
    'title': '南宁公共',
  },
];

final dns = [
  {'domain': 'api.themoviedb.org', 'id': 1, 'ip': '8.8.8.8'},
];
final downloadTasks = [
  {
    'createdAt': '+002024-12-28T13:28:12.000000000Z',
    'elapsed': 8939,
    'id': 4,
    'mediaId': 1,
    'mediaType': 'movie',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/d2W9sA2l18bmpE7w74mlxQ6kMp.jpg',
    'progress': 0.2916521430015564,
    'size': 19323377131,
    'speed': null,
    'status': 'idle',
    'title': '疯狂元素城',
  },
];

final series = [
  {
    'actors': [],
    'firstAirDate': '2016-01-14',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/rvZJxD36tKoglL8fXoMMWKGQfM.jpg',
    'country': 'JP',
    'favorite': false,
    'filename': '为美好的世界献上祝福！ (2016)',
    'genres': [],
    'id': 6,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/9ao3YjNJuezcnxv9Bmr0NQk9FSf.png',
    'nextToPlay': null,
    'originalTitle': 'この素晴らしい世界に祝福を！',
    'overview':
        '热爱游戏的家里蹲少年·佐藤和真的人生，因交通事故而轻易闭幕……本该是这样，但当他醒来之时，眼前有一位自称是女神的美少女。“喂，我有点好事要告诉你。要去异世界吗？只带一样你喜欢的东西没问题喔。”“那，我就带着你好了。”由此开始，在异世界转生的和真的魔王讨伐大冒险开始了……虽然是这么想的，但他却为了获得衣食住行而开始劳动。想要平稳度日的和真，却由于女神引起的各种问题，而终于被魔王军盯上了',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/wVrnWi9rUXAH22u6upt6u8eRW5a.jpg',
    'scrapper': {'id': '65844', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Ended',
    'studios': [],
    'themeColor': 12171709,
    'title': '为美好的世界献上祝福！',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:14.0 +00:00:00',
    'voteAverage': 8.581999778747559,
    'voteCount': 1319,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2012-10-02',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/cttisz5q4LHwyRYlIj9S7oQa27v.jpg',
    'country': 'JP',
    'favorite': false,
    'filename': '元气少女缘结神',
    'genres': [],
    'id': 8,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/j3J8I95FfK96dqXYjQs9Bh6pRrZ.png',
    'nextToPlay': null,
    'originalTitle': '神様はじめました',
    'overview':
        '桃园奈奈生因好赌的父亲在欠下一屁股债后离家出走，被赶出去流落街头的时候帮助了一位被狗追到树下的神秘男人，神秘男人知道她的遭遇后说：“那我把我的家给你吧！”，于是无家可归的奈奈生在半信半疑之下前往那个"家"，发现那竟是一间荒废许久的神社，还出现一个狐狸妖怪，自称是侍奉土地神的狐妖巴卫，而神秘男人竟然是土地神，神秘男人把家让给她，也就是连土地神的职位也一并交给她，从此奈奈生开始了当土地神之路……',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/8nfyyLqcAbEocNvPXj26uIflThp.jpg',
    'scrapper': {'id': '62741', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Ended',
    'studios': [],
    'themeColor': 12039349,
    'title': '元气少女缘结神',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:14.0 +00:00:00',
    'voteAverage': 8.600000381469727,
    'voteCount': 936,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2019-10-08',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/zBfnpI8883yeQkXK2kpLavHv9Yw.jpg',
    'country': 'US',
    'favorite': false,
    'filename': '史前战纪 (2019)',
    'genres': [],
    'id': 12,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/hwlZlgTPMAoHdE7DA9Fil7K6EDr.png',
    'nextToPlay': null,
    'originalTitle': 'Primal',
    'overview': '《史前战纪》讲述一个正走向进化之路的穴居人以及一只濒临灭绝的恐龙，他们因为悲剧而意外地成为朋友，一人一兽得联合起来才能在这暴力的原始世界中生存下去。',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/cZ8JUIwS9K4kttelRq6eP0mVhjK.jpg',
    'scrapper': {'id': '89456', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Returning Series',
    'studios': [],
    'themeColor': 14382193,
    'title': '史前战纪',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:12.0 +00:00:00',
    'voteAverage': 8.616000175476074,
    'voteCount': 1416,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2024-01-18',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/tuCU2yVRM2iZxFkpqlPUyvd6tSu.jpg',
    'country': 'US',
    'favorite': false,
    'filename': '地狱客栈 (2024)',
    'genres': [],
    'id': 14,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/r91aVEvQjmbR3NTbTPvqrziInHv.png',
    'nextToPlay': null,
    'originalTitle': 'Hazbin Hotel',
    'overview': '地狱公主夏莉·晨星努力说服一众恶魔与天使，地狱的灵魂可以被救赎。这部有歌唱有咒骂的成人音乐喜剧讲述灵魂获得第二次机会的故事。',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/7hIhuP9T0d8WOqvqxfuLqgXaxPW.jpg',
    'scrapper': {'id': '94954', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Returning Series',
    'studios': [],
    'themeColor': 10236476,
    'title': '地狱客栈',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:13.0 +00:00:00',
    'voteAverage': 8.767000198364258,
    'voteCount': 1237,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2020-01-10',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/ifJacgrENUweJF5Kq8h2NYfShzd.jpg',
    'country': 'JP',
    'favorite': false,
    'filename': '地缚少年花子君',
    'genres': [],
    'id': 17,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/d7sRl6ABTPC2Sks0TWLegBykzuF.png',
    'nextToPlay': null,
    'originalTitle': '地縛少年花子くん',
    'overview': '海鸥学园的奇妙传言之一。据说旧校舍三层女厕所的第三间里的同学，会实现前来拜访者的愿望。非常喜欢巫术等超自然现象的少女八寻宁宁为了实现自己的愿望，将之托付给了学园怪谈……',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/cjZ1uZRH9rwKKN3uthNHAUp1xPn.jpg',
    'scrapper': {'id': '95269', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Returning Series',
    'studios': [],
    'themeColor': 12360024,
    'title': '地缚少年花子君',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:11.0 +00:00:00',
    'voteAverage': 8.633999824523926,
    'voteCount': 731,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2012-06-15',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/l0XvAI856XdyDYEfr1njztjH7u0.jpg',
    'country': 'US',
    'favorite': false,
    'filename': '怪诞小镇 (2012)',
    'genres': [],
    'id': 23,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/jIBKuOUNjpS42viCVmGFklpKj4i.png',
    'nextToPlay': null,
    'originalTitle': 'Gravity Falls',
    'overview':
        '暑假到了，双胞胎姐弟俩梅宝（克里斯汀·沙尔 Kristen Schaal 配音）和迪普（杰森·雷特 Jason Ritter 配音）被爸妈赶到一个偏僻小镇“重力泉”过暑假，在这里，他们的斯坦叔公经营着一家专门敲诈游客的旅游景点“神秘小屋”，其中有着各种各样稀奇古怪的东西。然而更让人感到毛骨悚然的，则是这个怪诞小镇里的森林。为人慎重、头脑聪明的迪普觉察到森林的异样，继而发现了一本埋在地下的神秘笔记本，里面记载着存在于神秘小镇的不为人知的秘密。乐天派的梅宝和机智的迪普，结识了神秘小屋的店员温蒂和苏斯，还遇到各种奇妙的小镇居民。在怪诞小镇重力泉，他们经历了一系列奇异事件，小矮人，湖怪，蜡像，通灵者，他们这个暑假注定不平凡。',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/yIZXD8FVxLiuA1lutKIO1UOXoOn.jpg',
    'scrapper': {'id': '40075', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Ended',
    'studios': [],
    'themeColor': 5127213,
    'title': '怪诞小镇',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:13.0 +00:00:00',
    'voteAverage': 8.600000381469727,
    'voteCount': 3088,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2016-04-03',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/6wSSyRNeF9vBJ1h29nuw3vG9hZI.jpg',
    'country': 'JP',
    'favorite': false,
    'filename': '我的英雄学院',
    'genres': [],
    'id': 25,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/x2akyNYTkIUExuM46FaJ2NUcAlw.png',
    'nextToPlay': null,
    'originalTitle': '僕のヒーローアカデミア',
    'overview':
        '大部分的人类，在这个时代里都拥有名为“个性”的力量，但有力量之人却不一定都属于正义的一方。只要邪恶出现的地方，必定会有英雄挺身而出拯救众人。一名天生没有力量的少年——绿谷出久从小就憧憬一位顶尖英雄，而他的梦想就是成为伟大的英雄，可是，没有力量的他能实现自己的梦想吗？虽然困难重重，少年却依旧不放弃，朝著自己的目标勇往前进！',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/dmUuNVWAJumRkDNuauFaLSvga00.jpg',
    'scrapper': {'id': '65930', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Returning Series',
    'studios': [],
    'themeColor': 14073933,
    'title': '我的英雄学院',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:14.0 +00:00:00',
    'voteAverage': 8.63599967956543,
    'voteCount': 4970,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2018-07-06',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/fFA3I1ArhfTZptG1NDkhrFIjrDz.jpg',
    'country': 'JP',
    'favorite': false,
    'filename': '战栗杀机',
    'genres': [],
    'id': 26,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/9nTn5F8FQRprHSw6yki4O06JlPd.png',
    'nextToPlay': null,
    'originalTitle': 'BANANA FISH',
    'overview':
        '纽约。有着非凡的姿容，和卓越战斗力的少年·亚修。统领街头暴力团的他听到了，被手下所杀的男人在临死之际说出的“BANANA FISH”的神秘话语。与此同时，他与作为摄影师的助手来取材的日本少年·奥村英二相遇。两人决定一同追寻“BANANA FISH”之谜——',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/3GiB5Ybbhzt0ePRR2zgld9R56DB.jpg',
    'scrapper': {'id': '80564', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Ended',
    'studios': [],
    'themeColor': 12892850,
    'title': '战栗杀机',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:14.0 +00:00:00',
    'voteAverage': 8.586000442504883,
    'voteCount': 870,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2014-04-06',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/3mBtXzyOIzh5zJNEgHqIIYTPb6n.jpg',
    'country': 'JP',
    'favorite': false,
    'filename': '排球少年',
    'genres': [],
    'id': 28,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/4IcVSKtK0e5RIIpFnD29xU0P5mI.png',
    'nextToPlay': null,
    'originalTitle': 'ハイキュー!!',
    'overview':
        '童年时一次看电视转播的经历，在少年日向翔阳的心中种下了排球的种子。他在初中时代是排球部的主将，可是人丁寥落的排球部始终没有起色，唯一一场比赛也已惨败告终。在此之后，他终于如愿考入梦寐以求的学府乌野高中，并加入了该校的排球部。当年翔阳在电视上看到的正是乌野高中的比赛，如今这个学校的排球却正面临着衰败的命运。与宿命的对手和好友影山飞雄聚首于此，心怀排球梦想的少年们将团结一心，带领着乌野这名王者再度振翅高飞。',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/gpna2w6NF83I9LX2eQRCdBzz6kF.jpg',
    'scrapper': {'id': '60863', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Ended',
    'studios': [],
    'themeColor': 13814970,
    'title': '排球少年',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:13.0 +00:00:00',
    'voteAverage': 8.618000030517578,
    'voteCount': 1385,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2023-08-31',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/7BzmK4MWc0cj4hCxwWURt6TS6UR.jpg',
    'country': 'US',
    'favorite': false,
    'filename': '探险活宝：菲奥娜与蛋糕',
    'genres': [],
    'id': 29,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/u54jTt95BU27uCKmy2gWw0bzXfV.png',
    'nextToPlay': null,
    'originalTitle': 'Adventure Time: Fionna & Cake',
    'overview': '宝妹和皮姊在前冰霸王赛门帕特里克夫的帮助下穿梭多重宇宙进行冒险与自我探索之旅。',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/fi1b6U1kp73xheECzqwzMn8u3mX.jpg',
    'scrapper': {'id': '131378', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Returning Series',
    'studios': [],
    'themeColor': 12240843,
    'title': '探险活宝：菲奥娜与蛋糕',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:12.0 +00:00:00',
    'voteAverage': 8.800000190734863,
    'voteCount': 214,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2021-03-25',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/ohjinjQAEKxqdP5IK8TcUpLrKgE.jpg',
    'country': 'US',
    'favorite': false,
    'filename': '无敌少侠',
    'genres': [],
    'id': 31,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/zwJwLPuwx6s0vaVzWEE7EpL1mFd.png',
    'nextToPlay': null,
    'originalTitle': 'INVINCIBLE',
    'overview': '17岁时，马克格雷森从父亲那里继承来的超能力终于苏醒。他加入了父亲，成为地球上最伟大的英雄之一。这对他而言是美梦成真，但后来发生了一件震撼性事件，改变了一切。',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/qKGKemIogTDTfZoGZEt79V7HUGX.jpg',
    'scrapper': {'id': '95557', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Returning Series',
    'studios': [],
    'themeColor': 3617577,
    'title': '无敌少侠',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:13.0 +00:00:00',
    'voteAverage': 8.640000343322754,
    'voteCount': 4798,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2023-01-15',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/lY2DhbA7Hy44fAKddr06UrXWWaQ.jpg',
    'country': 'US',
    'favorite': false,
    'filename': '最后生还者',
    'genres': [],
    'id': 33,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/msYtgZbEo8tAOJ37T50kgqulpKf.png',
    'nextToPlay': null,
    'originalTitle': 'The Last of Us',
    'overview':
        '在现代文明被摧毁的二十年后，人类因现代传染病而面临绝种危机，幸存的人类为了生存自相残杀。中年男性走私犯乔尔（佩德罗·帕斯卡饰）为了完成“火萤”组织首领玛琳（梅尔·丹德里奇饰）的托付，带着14岁少女艾莉（贝拉·拉姆齐饰）一同踏出由军队保护的疫情隔离区，穿越化为废墟丛林的大都会。面对病毒感染变种人类与其他幸存者集团威胁，展开了一场改变两人一生的深刻旅程。',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/c9H1vkVepqyE5R03Yi9eWbaIN8H.jpg',
    'scrapper': {'id': '100088', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Returning Series',
    'studios': [],
    'themeColor': 2763562,
    'title': '最后生还者',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:11.0 +00:00:00',
    'voteAverage': 8.600000381469727,
    'voteCount': 5426,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2024-08-09',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/jmV6NIzZxGzRoljFPwao6sh4Nny.jpg',
    'country': 'MX',
    'favorite': false,
    'filename': '没有人会想念我们 (2024)',
    'genres': [],
    'id': 37,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': null,
    'nextToPlay': null,
    'originalTitle': 'Nadie nos va a extrañar',
    'overview': null,
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/py0s87C9214KRbZ4kWLQfgsE9ET.jpg',
    'scrapper': {'id': '259666', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Ended',
    'studios': [],
    'themeColor': 4403494,
    'title': '没有人会想念我们',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:14.0 +00:00:00',
    'voteAverage': 8.666999816894531,
    'voteCount': 224,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '1993-10-16',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/5bNQtKzufiAbwUpU1jWDwUIOVlm.jpg',
    'country': 'JP',
    'favorite': false,
    'filename': '灌篮高手 (1993)',
    'genres': [],
    'id': 39,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/7I4Hwg8g1CUYpDMFGlbyDOYzvMq.png',
    'nextToPlay': null,
    'originalTitle': 'スラムダンク',
    'overview':
        '湘北高中的一年级新生樱木花道在初中就有了被50个女孩抛弃的“悲惨”经历，最后一个女孩抛弃他原来是看上了篮球部队小田，由此樱木对篮球更是深恶痛绝。进入高中后，樱木看上了美少女赤木晴子，晴子十分热爱篮球，为了赢取晴子的芳心，樱木决定加入篮球部。在侥幸赢得与篮球队队长赤木刚宪的打赌后，樱木顺利加入了篮球队。随着国中篮球联赛的最有价值球员流川枫的到来、伤愈复出的控位宫城良田以及误入歧途的前国中最有价值球员三井寿的回归，去年不堪一击的湘北篮球今年可谓人强马壮，虽然问题少年一大帮，但是在队长赤木刚宪的带领下，这一群以全国第一为目标的篮球少年正朝着自己的梦想进发！',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/c6oBt7aD6V4JzPhzHTqMH4xPO7O.jpg',
    'scrapper': {'id': '42573', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Ended',
    'studios': [],
    'themeColor': 13001022,
    'title': '灌篮高手',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:52.0 +00:00:00',
    'voteAverage': 8.600000381469727,
    'voteCount': 912,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2020-01-10',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/mGHrUSt2uA5RaIheSmBfRnRHPS8.jpg',
    'country': 'US',
    'favorite': false,
    'filename': '猫头鹰魔法社 (2020)',
    'genres': [],
    'id': 43,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/2Jj07dFN8Eh1H8LN0Ccaig25k8G.png',
    'nextToPlay': null,
    'originalTitle': 'The Owl House',
    'overview':
        '露丝是一个自信的人类少女，她偶然发现了一个通往魔法新世界的入口，在那里她结识了叛逆的女巫伊丹和可爱的小战士魔王。尽管没有魔法能力，露丝还是选择在猫头鹰魔法社给伊丹当学徒，来实现自己成为女巫的梦想，并最终在这个地方找到了新家庭。',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/zqjSex7DZn7p4dU7mMktdJ8zQV5.jpg',
    'scrapper': {'id': '92685', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Ended',
    'studios': [],
    'themeColor': 5069492,
    'title': '猫头鹰魔法社',
    'trailer': null,
    'updateAt': '2025-03-22 12:16:25.0 +00:00:00',
    'voteAverage': 8.661999702453613,
    'voteCount': 1651,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2000-10-03',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/2w8FaLwwJTWr6ExUMeVgT2Th5YT.jpg',
    'country': 'JP',
    'favorite': false,
    'filename': '第一神拳 (2000)',
    'genres': [],
    'id': 46,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/gSsGDsLPoA3HfFIMXn5muqGzcE5.png',
    'nextToPlay': null,
    'originalTitle': 'はじめの一歩',
    'overview':
        '电视动画《第一神拳》由MADHOUSE制作改编自日本漫画家森川让次原作的同名漫画。动画于2000年10月3日起在日本电视台首播，全76话.\n\n电视动画《第一神拳 New Challenger》于2009年1月6日播出，全26话.\n\n电视动画《第一神拳 Rising》于2013年10月5日播出，全25话.\n\n电视动画剧场版《第一神拳 Champion Road》于2003年4月18日播出.\n\n60分钟OVA《第一神拳 间柴vs木村 死刑执行》于2003年9月5日发售.',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/rxiMbMzyyEWueFL9tuR9XKlo3e1.jpg',
    'scrapper': {'id': '42705', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Ended',
    'studios': [],
    'themeColor': 12957870,
    'title': '第一神拳',
    'trailer': null,
    'updateAt': '2025-03-22 12:24:26.0 +00:00:00',
    'voteAverage': 8.699999809265137,
    'voteCount': 1102,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2008-01-20',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/9faGSFi5jam6pDWGNd0p8JcJgXQ.jpg',
    'country': 'US',
    'favorite': false,
    'filename': '绝命毒师 (2008)',
    'genres': [],
    'id': 47,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/chw44B2VnLha8iiTdyZcIW0ZELC.png',
    'nextToPlay': null,
    'originalTitle': 'Breaking Bad',
    'overview':
        '新墨西哥州的高中化学老师沃尔特·H·怀特是拮据家庭的唯一经济来源。他大半生安分守己，兢兢业业，却在50岁生日之际突然得知自己罹患肺癌晚期的噩耗，原本便不甚顺意的人生顿时雪上加霜。为了保障怀孕的妻子斯凯勒和残疾的儿子小沃特能在自己死后衣食无忧，沃尔特决意铤而走险。他主动找到曾经的学生、而今的毒贩小混混杰西·平克曼谈合作，并运用娴熟高超的化学技术提炼出高纯度冰毒交给后者贩售。孰料事态的发展却在平克曼带回毒品供销商疯狂小八及其表弟后急转直下，沃尔特的人生也由此彻底步向失控。他被迫开始了教书与制毒的双重生活，逐渐坠落至万劫不复的深渊。',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/bSldznJEjkeojc5dzjLvlukqVEU.jpg',
    'scrapper': {'id': '1396', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Ended',
    'studios': [],
    'themeColor': 1319183,
    'title': '绝命毒师',
    'trailer': null,
    'updateAt': '2025-03-22 12:22:43.0 +00:00:00',
    'voteAverage': 8.92199993133545,
    'voteCount': 15230,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2024-10-04',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/j67Wi1mzPxPVVybjmaIsvzsqFDH.jpg',
    'country': 'JP',
    'favorite': false,
    'filename': '胆大党',
    'genres': [],
    'id': 48,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/dYTYlK1YarNQ5BV2akmA7w3PgCh.png',
    'nextToPlay': null,
    'originalTitle': 'ダンダダン',
    'overview':
        '出生于灵媒师家族的女高中生·小桃（绫濑桃），与她同年级的超自然爱好者·厄卡伦（高仓健）。小桃在厄卡伦遭到班上同学欺凌时保护了他，两人以此为契机开始有了交流。“相信幽灵存在但否定外星人存在”的小桃，和“相信外星人存在但否定幽灵存在”的厄卡伦争论不休。为了让对方相信外星人和幽灵的存在，小桃去了被称为UFO圣地的废弃医院，厄卡伦去了闹鬼的隧道。在那里，他们遇到了无法理解的极其怪异的现象。在绝境中，小桃觉醒了体内潜藏的力量，厄卡伦获得了诅咒之力，二人开始挑战接连逼近的怪异！也开始了命运之恋！？超能力战斗&青春故事，开幕！',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/tvLkaxvMXM2I1NSoUE28EFaTUs5.jpg',
    'scrapper': {'id': '240411', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Returning Series',
    'studios': [],
    'themeColor': 4992045,
    'title': '胆大党',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:13.0 +00:00:00',
    'voteAverage': 8.800000190734863,
    'voteCount': 437,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2021-11-06',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/wQEW3xLrQAThu1GvqpsKQyejrYS.jpg',
    'country': 'US',
    'favorite': false,
    'filename': '英雄联盟：双城之战 (2021)',
    'genres': [],
    'id': 49,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/jXLNOzeEA8AoJy92dJTUUZXTMxK.png',
    'nextToPlay': null,
    'originalTitle': 'Arcane',
    'overview':
        '本动画剧集以游戏《英雄联盟》为背景，讲述了在充满蒸汽朋克气息的乌托邦——皮尔特沃夫和由化学品驱动的地下城——祖安中，蔚和金克丝姐妹俩，在一场由神秘的海克斯科技引发的激烈冲突中站在了彼此的对立面，她们从此分道扬镳，朝着不同的命运终点走去，但心中的羁绊又无时不刻地让二人想要破镜重圆，而心怀正义的姐姐蔚也拼尽全力，誓要战胜地下城中的一切邪恶。',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/2vX3qtBa7qODr6ANC3m3SiwtYRj.jpg',
    'scrapper': {'id': '94605', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Ended',
    'studios': [],
    'themeColor': 6048847,
    'title': '英雄联盟：双城之战',
    'trailer': null,
    'updateAt': '2025-03-22 12:26:13.0 +00:00:00',
    'voteAverage': 8.800000190734863,
    'voteCount': 4978,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2023-09-29',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/96RT2A47UdzWlUfvIERFyBsLhL2.jpg',
    'country': 'JP',
    'favorite': false,
    'filename': '葬送的芙莉莲',
    'genres': [],
    'id': 51,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/yQuc8JcBxRWXfRHrNUSM47gCXOo.png',
    'nextToPlay': null,
    'originalTitle': '葬送のフリーレン',
    'overview':
        '打倒了魔王的勇者一行人的后日谈——在“那之后”的故事。身为魔法使的芙莉莲是一位精灵，她和另外三人有着不一样的地方。对于生活在“之后”的世界、感受到的事情有着不一样的看法……残存世间的人们所编织的，葬送与祈祷相伴的故事——从“冒险的结束”开始了。',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/jvueXfiDeeifwGCySYsQdcw2fCz.jpg',
    'scrapper': {'id': '209867', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Returning Series',
    'studios': [],
    'themeColor': 12630950,
    'title': '葬送的芙莉莲',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:12.0 +00:00:00',
    'voteAverage': 8.77299976348877,
    'voteCount': 401,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2017-10-29',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/1nfIEJu02Zhv9omTKkzwHnK8Dji.jpg',
    'country': 'GB',
    'favorite': false,
    'filename': '蓝色星球2',
    'genres': [],
    'id': 52,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/842J3S1LQhIcn4KFgKRUmtDsZ0w.png',
    'nextToPlay': null,
    'originalTitle': 'Blue Planet II',
    'overview':
        '自然界中，没有什么地方会比大海更让人类心驰向往，那里狂野令人印象深刻，但也充满无穷魅力，让人神魂颠倒。人类奔向地球上面积最广阔，但又知之甚少的海洋，进行一次紧张激烈的探险。从冰雪覆盖的极地海域到颜色变幻无穷的珊瑚岛礁；从风暴袭扰的大西洋到伸手不见五指、充满奇特物种的漆黑深海海底；人类体验海洋最为野性的一面，去认识那些令人惊异的新景观，匪夷所思的新生物物种。',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/nrDExNUKpEKHnsazWR4PFQppSDa.jpg',
    'scrapper': {'id': '74313', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Ended',
    'studios': [],
    'themeColor': 1602967,
    'title': '蓝色星球2',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:11.0 +00:00:00',
    'voteAverage': 8.600000381469727,
    'voteCount': 277,
    'watched': false,
  },
  {
    'actors': [],
    'firstAirDate': '2017-06-19',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/gDDwXPs53PYNVM8LASxXOxtxmX5.jpg',
    'country': 'AR',
    'favorite': false,
    'filename': '逐梦绿茵场',
    'genres': [],
    'id': 56,
    'keywords': [],
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/mYFOdJWIm3gZh5s5tOOiapBIAwF.png',
    'nextToPlay': null,
    'originalTitle': 'O11CE',
    'overview':
        '剧集讲述了热爱足球，与祖母住在干白杨小镇的少年加博·莫雷蒂（马里亚诺·冈萨雷斯饰）的故事。著名的体育学院（IAD）的主教练弗朗西斯科（尼古拉斯·保罗斯饰）注意到了他出色的球技，并决定给他颁发奖学金。加博开始了前往布宜诺斯艾利斯，住进IAD宿舍的冒险之旅。他的梦想是成为一名伟大的足球运动员，但他不知道的是，在这期间，命运将会让他发现自己的家庭秘密。',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/w9e9YvhXVXR1PjTz79YmbhAhNOo.jpg',
    'scrapper': {'id': '72637', 'type': 'tmdb'},
    'seasons': [],
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Ended',
    'studios': [],
    'themeColor': 5511188,
    'title': '逐梦绿茵场',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:11.0 +00:00:00',
    'voteAverage': 8.600000381469727,
    'voteCount': 1467,
    'watched': false,
  },
  {
    'firstAirDate': '2019-04-06',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg',
    'country': 'JP',
    'favorite': false,
    'filename': '鬼灭之刃',
    'id': 61,
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/ecghlDeabR3X3Vv8tXIOeXHQvQe.png',
    'originalTitle': '鬼滅の刃',
    'overview':
        '时值日本大正时期。\n\n传说太阳下山后，有恶鬼出没吃人。亦有猎鬼人斩杀恶鬼、保护人们。\n\n卖炭少年炭治郎，他那平凡而幸福的日常生活，在家人遭到恶鬼袭击的那一天发生了剧变。母亲与四个弟弟妹妹惨遭杀害，而与他一起生还的妹妹祢豆子亦异变成凶暴的鬼。\n\n在猎鬼人的指引下，立志成为猎鬼人的炭治郎与变成鬼却尚存理智的祢豆子踏上了旅程。通过艰苦的剑术修行与赌命试炼，炭治郎成为了猎鬼人组织“鬼杀队”的一员。\n\n为了让妹妹祢豆子变回人类，为了讨伐杀害家人的恶鬼，为了斩断悲伤的连锁，少年与鬼的战斗不曾停歇。\n\n幸福被破坏之时，总是弥漫着鲜血的味道。纵然我身俱灭，定将恶鬼斩杀！血风剑戟冒险谭，开幕！',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/8yL6oB8eGvnbJr4W1fTdHrI103R.jpg',
    'scrapper': {'id': '85937', 'type': 'tmdb'},
    'skipEnding': null,
    'skipIntro': null,
    'status': 'Ended',
    'themeColor': 14526561,
    'title': '鬼灭之刃',
    'trailer': null,
    'updateAt': '2025-03-22 12:03:12.0 +00:00:00',
    'voteAverage': 8.651000022888184,
    'voteCount': 6612,
    'watched': false,
    'mediaCast': actors,
    'mediaCrew': actors,
    'genres': genres,
    'keywords': keywords,
    'nextToPlay': {
      'actors': actors,
      'airDate': '2023-04-09',
      'backdrop': null,
      'downloaded': null,
      'duration': null,
      'episode': 1,
      'ext': 'mp4',
      'favorite': false,
      'fileSize': 0,
      'filename': '1',
      'id': 2314,
      'lastPlayedPosition': null,
      'lastPlayedTime': null,
      'logo': null,
      'originalTitle': null,
      'overview': '一个多世纪以来，首例上弦之鬼的死亡在鬼之间引发涟漪。炭治郎前往刀匠村锻造新刀。',
      'poster': 'https://image.tmdb.org/t/p/w1280_and_h720_bestv2/nIiUkcBobhVoBh02RnXRaS5KW3U.jpg',
      'season': 4,
      'seasonId': 61,
      'seasonTitle': null,
      'seriesId': 61,
      'seriesTitle': '鬼灭之刃',
      'skipEnding': null,
      'skipIntro': null,
      'subtitles': [],
      'themeColor': 11907002,
      'title': '某人的梦',
      'updateAt': '2025-03-22 13:22:53.0 +00:00:00',
      'url': '/file/download?id=17bad23e71c246068ed8a8e22d902eb9',
      'watched': false,
    },
    'seasons': seasons,
    'studios': studios,
  },
];

final movies = [
  {
    'releaseDate': '2023-06-14',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/6YInbRTk39ckuLYFmUgBCKcKNjb.jpg',
    'country': 'United States of America',
    'downloaded': null,
    'duration': 1231344,
    'ext': 'mkv',
    'favorite': false,
    'fileSize': 19323377131,
    'filename': '疯狂元素城 (2023)',
    'id': 1,
    'fileId': '1',
    'lastPlayedPosition': 643253,
    'lastPlayedTime': DateTime.now().subtract(const Duration(hours: 2)).toString(),
    'logo': 'https://image.tmdb.org/t/p/w500/aYT1V9U0LjgCosicUA3oLnFF53x.png',
    'originalTitle': 'Elemental',
    'overview':
        '曾几何时，火焰一族的火柱和怀孕的妻子灯花背井离乡，远渡重洋，来到了元素城开始新的生活。经过十数年的经营，火柱老板的杂货店开得有声有色，而气竭力衰的他也开始琢磨将这家店传给开朗热情却脾气火爆的独生女小焰。在独自筹备某次促销活动时，小焰家的地下室管道出现意外，她也进而邂逅了水一族的青年渡阿波。阿波感性善良，作为市政府检查员，他不得不准备给这家店开出罚单。可是，这个店凝聚了小焰父亲全部的心血啊！为了阻止阿波，小焰使出浑身解数。而就在这一过程中，水火不相容的两个人开始尝试了解对方…',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/d2W9sA2l18bmpE7w74mlxQ6kMp.jpg',
    'scrapper': {'id': '976573', 'type': 'tmdb'},
    'status': 'Released',
    'subtitles': [],
    'themeColor': 10462395,
    'title': '疯狂元素城',
    'trailer': null,
    'updateAt': '2025-03-14 06:37:34.0 +00:00:00',
    'url': '',
    'voteAverage': 7.618000030517578,
    'voteCount': 4705,
    'watched': false,
    'mediaCast': [
      {
        'adult': false,
        'role': 'Ember (voice)',
        'gender': 1,
        'id': 469,
        'name': '莉娅·刘易斯',
        'originalName': 'Leah Lewis',
        'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/liV9OXUeo7T19hhjFlqTELtETnW.jpg',
        'scrapper': {'id': '1087262', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Wade (voice)',
        'gender': 2,
        'id': 470,
        'name': '马莫多·阿西',
        'originalName': 'Mamoudou Athie',
        'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/ycUbhfZRKC8MtNK9oMwscRsl3uM.jpg',
        'scrapper': {'id': '1639848', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Bernie (voice)',
        'gender': 2,
        'id': 471,
        'name': '罗尼·德尔·卡门',
        'originalName': 'Ronnie del Carmen',
        'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/lPCmkQK76DOgkmcRjg9394QPyAu.jpg',
        'scrapper': {'id': '1236458', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Cinder (voice)',
        'gender': 1,
        'id': 472,
        'name': '希拉·沃索夫',
        'originalName': 'Shila Ommi',
        'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/i9m2RGrANNxidj0bVKlSs0zHPNX.jpg',
        'scrapper': {'id': '2073564', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Gale (voice)',
        'gender': 1,
        'id': 473,
        'name': '温迪·麦丽登·康薇',
        'originalName': 'Wendi McLendon-Covey',
        'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/d8VKC8Ms3u9XiW4e4jsy2grP02d.jpg',
        'scrapper': {'id': '63234', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Brook (voice)',
        'gender': 1,
        'id': 474,
        'name': '凯瑟琳·欧哈拉',
        'originalName': "Catherine O'Hara",
        'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/cMBxHeztNVc8YXKcj084Mdd3f3U.jpg',
        'scrapper': {'id': '11514', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Clod (voice)',
        'gender': 0,
        'id': 475,
        'name': '梅森·韦特海默',
        'originalName': 'Mason Wertheimer',
        'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/vpjZTxItJMpkjFrls2kpVnJq1H.jpg',
        'scrapper': {'id': '3983226', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Harold (voice)',
        'gender': 2,
        'id': 476,
        'name': '罗诺比尔·拉希里',
        'originalName': 'Ronobir Lahiri',
        'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/uZQu5zBGxE62uGP7qaGhjQ79bn3.jpg',
        'scrapper': {'id': '1217619', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Flarrietta (voice)',
        'gender': 1,
        'id': 477,
        'name': '威尔玛·博尼特',
        'originalName': 'Wilma Bonet',
        'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/2YC8C8FXWQZ4UXv3wAkWUtmqJLY.jpg',
        'scrapper': {'id': '1576334', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Fern (voice)',
        'gender': 2,
        'id': 478,
        'name': '乔·佩拉',
        'originalName': 'Joe Pera',
        'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/lzf1mnclmHo4y53ZpvtlkWgFunZ.jpg',
        'scrapper': {'id': '1663974', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Alan / Lutz / Earth Pruner (voice)',
        'gender': 2,
        'id': 479,
        'name': '马修·杨·金',
        'originalName': 'Matthew Yang King',
        'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/jcLJIw0s2uP4PSnH5E8oM3pUyiV.jpg',
        'scrapper': {'id': '157067', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Little Kid Ember (voice)',
        'gender': 1,
        'id': 480,
        'name': 'Clara Lin Ding',
        'originalName': 'Clara Lin Ding',
        'profile': null,
        'scrapper': {'id': '4078463', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Big Kid Ember (voice)',
        'gender': 1,
        'id': 481,
        'name': '杜采融',
        'originalName': 'Reagan To',
        'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/xrmRnIi9RxGeBYOl50aLtdCdiJd.jpg',
        'scrapper': {'id': '1937823', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Sparkler Customer (voice)',
        'gender': 2,
        'id': 482,
        'name': '杰夫·拉彭西',
        'originalName': 'Jeff Lapensee',
        'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/hXCk1ZUUOxVMrEdCFqQtnxYB9o4.jpg',
        'scrapper': {'id': '4078465', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Wood Immigration Official (voice)',
        'gender': 0,
        'id': 483,
        'name': 'Ben Morris',
        'originalName': 'Ben Morris',
        'profile': null,
        'scrapper': {'id': '1997753', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Flarry (voice)',
        'gender': 2,
        'id': 484,
        'name': '喬納森·亞當斯',
        'originalName': 'Jonathan Adams',
        'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/mkgyl2MciZ14wsYi6zedyj6hnR8.jpg',
        'scrapper': {'id': '13477', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Customer / Delivery Person / Earth Landlord (voice)',
        'gender': 1,
        'id': 485,
        'name': 'Alex Kapp',
        'originalName': 'Alex Kapp',
        'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/qpVxC6GgYaTg6iyPWV93u0i4JKK.jpg',
        'scrapper': {'id': '1211955', 'type': 'tmdb'},
      },
      {
        'adult': false,
        'role': 'Doorman (voice)',
        'gender': 2,
        'id': 486,
        'name': 'P.L. Brown',
        'originalName': 'P.L. Brown',
        'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/6sH4laBWYn3rPg6BQSe5mDYJBSe.jpg',
        'scrapper': {'id': '1906860', 'type': 'tmdb'},
      },
    ],
    'genres': [
      {
        'id': 2,
        'name': '喜剧',
        'scrapper': {'id': '35', 'type': 'tmdb'},
      },
      {
        'id': 4,
        'name': '家庭',
        'scrapper': {'id': '10751', 'type': 'tmdb'},
      },
      {
        'id': 5,
        'name': '动画',
        'scrapper': {'id': '16', 'type': 'tmdb'},
      },
      {
        'id': 11,
        'name': '奇幻',
        'scrapper': {'id': '14', 'type': 'tmdb'},
      },
      {
        'id': 12,
        'name': '爱情',
        'scrapper': {'id': '10749', 'type': 'tmdb'},
      },
    ],
    'keywords': [
      {
        'id': 72,
        'name': 'fire',
        'scrapper': {'id': '657', 'type': 'tmdb'},
      },
      {
        'id': 73,
        'name': 'earth',
        'scrapper': {'id': '4627', 'type': 'tmdb'},
      },
      {
        'id': 74,
        'name': 'computer animation',
        'scrapper': {'id': '10159', 'type': 'tmdb'},
      },
      {
        'id': 75,
        'name': 'duringcreditsstinger',
        'scrapper': {'id': '179431', 'type': 'tmdb'},
      },
      {
        'id': 76,
        'name': 'elements',
        'scrapper': {'id': '268053', 'type': 'tmdb'},
      },
      {
        'id': 77,
        'name': 'water',
        'scrapper': {'id': '271672', 'type': 'tmdb'},
      },
      {
        'id': 78,
        'name': 'city',
        'scrapper': {'id': '282997', 'type': 'tmdb'},
      },
      {
        'id': 79,
        'name': 'hopeful',
        'scrapper': {'id': '325824', 'type': 'tmdb'},
      },
    ],
    'studios': [
      {
        'country': 'US',
        'id': 42,
        'logo': 'https://image.tmdb.org/t/p/h50/wdrCwmRnLFJhEoH8GSfymY85KHT.png',
        'name': 'Walt Disney Pictures',
        'scrapper': {'id': '2', 'type': 'tmdb'},
      },
      {
        'country': 'US',
        'id': 43,
        'logo': 'https://image.tmdb.org/t/p/h50/1TjvGVDMYsj6JBxOAkUHpPEwLf7.png',
        'name': 'Pixar',
        'scrapper': {'id': '3', 'type': 'tmdb'},
      },
    ],
  },
  {
    'actors': [],
    'releaseDate': '2023-04-05',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg',
    'country': 'Japan,United States of America',
    'downloaded': null,
    'duration': 1831344,
    'ext': 'mkv',
    'favorite': false,
    'fileSize': 17622300595,
    'filename': '超级马力欧兄弟大电影 (2023)',
    'genres': [],
    'id': 2,
    'fileId': '1',
    'keywords': [],
    'lastPlayedPosition': 212445,
    'lastPlayedTime': DateTime.now().subtract(const Duration(hours: 2)).toString(),
    'logo': 'https://image.tmdb.org/t/p/w500/IoNbZB5Fjq3UV1STluNcT5MPK0.png',
    'originalTitle': 'The Super Mario Bros. Movie',
    'overview':
        '马力欧（克里斯·帕拉特 Chris Pratt 配音）和路易吉（查理·戴 Charlie Day 饰）是生活在布鲁克林的两名水管工，他们刚刚成立了自己的小公司，但很显然，他们的家人并不完全支持兄弟两人的这份事业。某日，在工作中，马力欧和路易吉被水管吸入到了一个光怪陆离的世界之中，两人在旅途中被迫分开，马力欧来到了由碧姬公主（安雅·泰勒-乔伊 Anya Taylor-Joy 配音）统治的蘑菇王国，而路易吉则不幸的被传送到了由酷霸王（杰克·布莱克 Jack Black 配音）统治的库巴王国。此时，酷霸王正准备大举进攻蘑菇国，掳走公主并和她结婚，在这个节骨眼上，马力欧的出现带给了碧姬公主希望，她带着马力欧来到了丛林王国，请求那里的国王和王子（塞斯·罗根 Seth Aaron Rogen 饰）的支援。',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/lZVumU6dplne9LpitkVDYxhKSDl.jpg',
    'scrapper': {'id': '502356', 'type': 'tmdb'},
    'status': 'Released',
    'studios': [],
    'subtitles': [],
    'themeColor': 10437201,
    'title': '超级马里奥兄弟大电影',
    'trailer': null,
    'updateAt': '2025-03-14 06:37:34.0 +00:00:00',
    'url': '',
    'voteAverage': 7.626999855041504,
    'voteCount': 9512,
    'watched': false,
  },
  {
    'actors': [],
    'releaseDate': '2022-11-11',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/4tdV5AeojEdbvn6VpeQrbuDlmzs.jpg',
    'country': 'Japan',
    'downloaded': null,
    'duration': null,
    'ext': 'mkv',
    'favorite': false,
    'fileSize': 11808497560,
    'filename': '铃芽之旅 (2022)',
    'genres': [],
    'id': 3,
    'fileId': '1',
    'keywords': [],
    'lastPlayedPosition': null,
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/j95d59MJe64aM2NLyjPKMh5tg7Y.png',
    'originalTitle': 'すずめの戸締まり',
    'overview':
        '生活在日本九州田舍的17岁少女・铃芽遇见了为了寻找“门”而踏上旅途的青年。追随着青年的脚步，铃芽来到了山上一片废墟之地，在这里静静伫立着一扇古老的门，仿佛是坍塌中存留的唯一遗迹。铃芽仿佛被什么吸引了一般，将手伸向了那扇门…  不久之后，日本各地的门开始一扇一扇地打开。据说，开着的门必须关上，否则灾祸将会从门的那一边降临于现世。  星星，夕阳，拂晓，误入之境的天空，仿佛溶解了一切的时间。在神秘之门的引导下，铃芽踏上了关门的旅途。',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/newKNDhIMnDylqzFedFzWZsXqxw.jpg',
    'scrapper': {'id': '916224', 'type': 'tmdb'},
    'status': 'Released',
    'studios': [],
    'subtitles': [],
    'themeColor': 6198186,
    'title': '铃芽之旅',
    'trailer': null,
    'updateAt': '2025-03-14 06:37:34.0 +00:00:00',
    'url': '',
    'voteAverage': 7.939000129699707,
    'voteCount': 1418,
    'watched': false,
  },
];

const actors = [
  {
    'adult': false,
    'role': '(voice)',
    'gender': 2,
    'id': 371,
    'name': '福原克己',
    'originalName': '福原かつみ',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/ijpwBGoo3iPmb9v1Oh4Fz9CFzOx.jpg',
    'scrapper': {'id': '2312002', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Tanjiro Kamado (voice)',
    'gender': 2,
    'id': 1974,
    'name': '花江夏树',
    'originalName': '花江夏樹',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/alTb0DlcPIbcwM08WSmxFai58sd.jpg',
    'scrapper': {'id': '1256603', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Nezuko Kamado (voice)',
    'gender': 1,
    'id': 1003,
    'name': '鬼头明里',
    'originalName': '鬼頭明里',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/AoRQOZRC0yINB0WeKnM569rV1wF.jpg',
    'scrapper': {'id': '1563442', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Zenitsu Agatsuma (voice)',
    'gender': 2,
    'id': 2049,
    'name': '下野纮',
    'originalName': '下野紘',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/yrSDcgFefHtWkFmLnTrcw2t0MV.jpg',
    'scrapper': {'id': '119145', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Inosuke Hashibira (voice)',
    'gender': 2,
    'id': 2102,
    'name': '松冈祯丞',
    'originalName': '松岡禎丞',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/ugDwdWEXnmv43jcbnfAi4XwiQ8C.jpg',
    'scrapper': {'id': '233590', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': '(voice),Kakushi (voice)',
    'gender': 2,
    'id': 947,
    'name': '高桥伸也',
    'originalName': '高橋伸也',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/19DN4yrD9c3E7BWthVEqvwhQNdb.jpg',
    'scrapper': {'id': '1157642', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Giyu Tomioka (voice)',
    'gender': 2,
    'id': 3885,
    'name': '樱井孝宏',
    'originalName': '櫻井孝宏',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/8s8owcKmpRAuhzEGjSdRpztthUg.jpg',
    'scrapper': {'id': '9705', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Genya Shinazugawa (voice)',
    'gender': 2,
    'id': 923,
    'name': '冈本信彦',
    'originalName': '岡本信彦',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/7s1K2yQVF5iIWILaOfG7QrMZkXA.jpg',
    'scrapper': {'id': '1245094', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Tengen Uzui (voice)',
    'gender': 2,
    'id': 1044,
    'name': '小西克幸',
    'originalName': '小西克幸',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/nYM5cH6U7cp4x9dIzW0enmEKmeV.jpg',
    'scrapper': {'id': '24647', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Muichiro Tokito (voice),Yuichiro Tokito (voice)',
    'gender': 2,
    'id': 3876,
    'name': '河西健吾',
    'originalName': '河西健吾',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/u59FdPSHlA7JCWNnX1m10neLfT.jpg',
    'scrapper': {'id': '1324472', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Mitsuri Kanroji (voice)',
    'gender': 1,
    'id': 215,
    'name': '花泽香菜',
    'originalName': '花澤香菜',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/rYbVloKRRK3gRTVAf3Mbj9xak4Z.jpg',
    'scrapper': {'id': '119143', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Matsuemon Tennoji (voice),Kasugai crow (voice)',
    'gender': 2,
    'id': 4557,
    'name': '山崎巧',
    'originalName': '山崎たくみ',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/wq8K3No0DUJsTCWDqparegOlGL6.jpg',
    'scrapper': {'id': '96728', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Kagaya Ubuyashiki (voice)',
    'gender': 2,
    'id': 755,
    'name': '森川智之',
    'originalName': '森川智之',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/u1N6H7V0dehFD4fcO7ZkHvIMUrG.jpg',
    'scrapper': {'id': '9706', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Shinobu Kocho (voice)',
    'gender': 1,
    'id': 4558,
    'name': '早见沙织',
    'originalName': '早見沙織',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/gLv9lO7dlUbIsmyJUvgegqAAXki.jpg',
    'scrapper': {'id': '221773', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Kyojuro Rengoku (voice)',
    'gender': 2,
    'id': 3861,
    'name': '日野聪',
    'originalName': '日野聡',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/8ZJIiwIVF2zDyyFr7oXewj0eEuu.jpg',
    'scrapper': {'id': '224413', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Muzan Kibutsuji (voice)',
    'gender': 2,
    'id': 4379,
    'name': '关俊彦',
    'originalName': '関俊彦',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/7jUPvx4hxWZWZJgyiCwd8KxWuvI.jpg',
    'scrapper': {'id': '90571', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': '(voice),Kakushi (voice)',
    'gender': 2,
    'id': 4559,
    'name': ' ',
    'originalName': '外崎友亮',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/txWqsedWOeZFQo72XmYnM1vEHbI.jpg',
    'scrapper': {'id': '2868405', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Hotaru Haganezuka (voice)',
    'gender': 2,
    'id': 2031,
    'name': '浪川大辅',
    'originalName': '浪川大輔',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/iw0X8oDutxaBAri3Ifga8nhdUJK.jpg',
    'scrapper': {'id': '110665', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Obanai Iguro (voice)',
    'gender': 2,
    'id': 4560,
    'name': '铃村健一',
    'originalName': '鈴村健一',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/vFqjmIjxfgBkh3ZmUin7QETV0sy.jpg',
    'scrapper': {'id': '9726', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Daki (voice)',
    'gender': 1,
    'id': 4561,
    'name': '泽城美雪',
    'originalName': '沢城みゆき',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/11mGqwpmu8CoEy1YJgabj2g7MIv.jpg',
    'scrapper': {'id': '186341', 'type': 'tmdb'},
  },
  {
    'adult': false,
    'role': 'Sanemi Shinazugawa (voice)',
    'gender': 2,
    'id': 1985,
    'name': '关智一',
    'originalName': '関智一',
    'profile': 'https://image.tmdb.org/t/p/w300_and_h450_bestv2/jGQC9KkfNMh2wBgizw81GLX2KN2.jpg',
    'scrapper': {'id': '90567', 'type': 'tmdb'},
  },
];

final seasons = [
  {
    'airDate': '2023-04-08',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg',
    'episodeCount': 11,
    'episodes': episodes,
    'favorite': false,
    'filename': null,
    'id': 61,
    'logo': 'https://image.tmdb.org/t/p/w500/ecghlDeabR3X3Vv8tXIOeXHQvQe.png',
    'overview': '《刀匠村篇》主角炭治郎在经过与上弦之陆的一场大战后，便在蝴蝶屋疗养了一段时间，在听说钢铁冢不再为自己打造新刀',
    'poster': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/xrhD9Pd82mVrCxsa4NXLb6CKs2d.jpg',
    'season': 4,
    'seriesTitle': '鬼灭之刃',
    'skipEnding': null,
    'skipIntro': null,
    'themeColor': 11907002,
    'title': '第4季 刀匠村篇',
    'updateAt': '2025-03-22 13:22:53.0 +00:00:00',
    'watched': false,
    'mediaCast': actors,
  },
];

final episodes = [
  {
    'fileId': '1',
    'mediaCast': actors,
    'airDate': '2023-04-09',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg',
    'downloaded': false,
    'duration': null,
    'episode': 1,
    'ext': 'mp4',
    'favorite': false,
    'fileSize': 0,
    'filename': '鬼灭之刃 - S04E01 - 某人的梦',
    'id': 2314,
    'lastPlayedPosition': null,
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/ecghlDeabR3X3Vv8tXIOeXHQvQe.png',
    'originalTitle': null,
    'overview': '一个多世纪以来，首例上弦之鬼的死亡在鬼之间引发涟漪。炭治郎前往刀匠村锻造新刀。',
    'poster': 'https://image.tmdb.org/t/p/w1280_and_h720_bestv2/nIiUkcBobhVoBh02RnXRaS5KW3U.jpg',
    'season': 4,
    'seasonId': 61,
    'seasonTitle': '第4季 刀匠村篇',
    'seriesId': 61,
    'seriesTitle': '鬼灭之刃',
    'skipEnding': null,
    'skipIntro': null,
    'subtitles': [],
    'themeColor': 11907002,
    'title': '某人的梦',
    'updateAt': '2025-03-22 13:25:52.0 +00:00:00',
    'url': '',
    'watched': false,
  },
  {
    'fileId': '1',
    'mediaCast': actors,
    'airDate': '2023-04-16',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg',
    'downloaded': false,
    'duration': 1421242,
    'episode': 2,
    'ext': 'mp4',
    'favorite': false,
    'fileSize': 0,
    'filename': '鬼灭之刃 - S04E02 - 缘一零式',
    'id': 2325,
    'lastPlayedPosition': 1312410,
    'lastPlayedTime': '2025-03-22 13:25:52',
    'logo': 'https://image.tmdb.org/t/p/w500/ecghlDeabR3X3Vv8tXIOeXHQvQe.png',
    'originalTitle': null,
    'overview':
        '因刀刃破损而惹怒了钢铁冢的炭治郎，与祢豆子一起前往刀匠们居住的村庄。在对鬼杀队士来说重要的据点之一，深藏的刀匠的村落，炭治郎与同期的不死川玄弥，恋柱·甘露寺蜜璃再会。从蜜璃那里听到秘密武器存在的炭治郎在山中寻找的时候，发现霞柱·时透无一郎和村子里的少年在争论着什么……',
    'poster': 'https://image.tmdb.org/t/p/w1280_and_h720_bestv2/uvT1yTTx3rfAIP8AtqxtSM0ZxRB.jpg',
    'season': 4,
    'seasonId': 61,
    'seasonTitle': '第4季 刀匠村篇',
    'seriesId': 61,
    'seriesTitle': '鬼灭之刃',
    'skipEnding': null,
    'skipIntro': null,
    'subtitles': [],
    'themeColor': 11907002,
    'title': '缘一零式',
    'updateAt': '2025-03-22 13:25:52.0 +00:00:00',
    'url': '',
    'watched': false,
  },
  {
    'fileId': '1',
    'mediaCast': actors,
    'airDate': '2023-04-23',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg',
    'downloaded': false,
    'duration': 1612410,
    'episode': 3,
    'ext': 'mp4',
    'favorite': false,
    'fileSize': 0,
    'filename': '鬼灭之刃 - S04E03 - 三百年以前的刀',
    'id': 2336,
    'lastPlayedPosition': 612410,
    'lastPlayedTime': '2025-03-22 13:25:52',
    'logo': 'https://image.tmdb.org/t/p/w500/ecghlDeabR3X3Vv8tXIOeXHQvQe.png',
    'originalTitle': null,
    'overview':
        '炭治郎和缘一零式开始训练，并被小铁坚持不懈的魔鬼式训练推向极限。通过这次训练，炭治郎掌握了一项新技能，即通过嗅觉预测对手的下一步行动会击中哪里。在训练中，炭治郎对缘一零式进行了一次打击，最终将其摧毁，但一把300多年前的剑从里面出现了...',
    'poster': 'https://image.tmdb.org/t/p/w1280_and_h720_bestv2/wquxWyBwsXG3lWrDjg7TQKSRfew.jpg',
    'season': 4,
    'seasonId': 61,
    'seasonTitle': '第4季 刀匠村篇',
    'seriesId': 61,
    'seriesTitle': '鬼灭之刃',
    'skipEnding': null,
    'skipIntro': null,
    'subtitles': [],
    'themeColor': 11907002,
    'title': '三百年以前的刀',
    'updateAt': '2025-03-22 13:25:52.0 +00:00:00',
    'url': '',
    'watched': false,
  },
  {
    'fileId': '1',
    'mediaCast': actors,
    'airDate': '2023-04-30',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg',
    'downloaded': false,
    'duration': null,
    'episode': 4,
    'ext': 'mp4',
    'favorite': false,
    'fileSize': 0,
    'filename': '鬼灭之刃 - S04E04 - 时透，谢谢你',
    'id': 2347,
    'lastPlayedPosition': null,
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/ecghlDeabR3X3Vv8tXIOeXHQvQe.png',
    'originalTitle': null,
    'overview':
        '在炭治郎和无一郎面前，突然出现了上弦的鬼。无一郎砍下鬼的脖子，鬼分裂成两个，无一郎被打飞。炭治郎和祢󠄀豆子、玄弥与两个鬼对峙，由于不停分裂的鬼发起了攻击，炭治郎也被拉开了。另一方面，无一郎在森林中救出了被金鱼鬼袭击的小铁——',
    'poster': 'https://image.tmdb.org/t/p/w1280_and_h720_bestv2/2HLP9LAcPkkzGbLpeKm33BXj4NE.jpg',
    'season': 4,
    'seasonId': 61,
    'seasonTitle': '第4季 刀匠村篇',
    'seriesId': 61,
    'seriesTitle': '鬼灭之刃',
    'skipEnding': null,
    'skipIntro': null,
    'subtitles': [],
    'themeColor': 11907002,
    'title': '时透，谢谢你',
    'updateAt': '2025-03-22 13:25:52.0 +00:00:00',
    'url': '',
    'watched': false,
  },
  {
    'fileId': '1',
    'mediaCast': actors,
    'airDate': '2023-05-07',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg',
    'downloaded': false,
    'duration': null,
    'episode': 5,
    'ext': 'mp4',
    'favorite': false,
    'fileSize': 0,
    'filename': '鬼灭之刃 - S04E05 - 赫刀',
    'id': 2349,
    'lastPlayedPosition': null,
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/ecghlDeabR3X3Vv8tXIOeXHQvQe.png',
    'originalTitle': null,
    'overview': '炭治郎赶到苦战中的祷豆子身边，展开来来往往的攻防战。 然而由于遭受可乐的团扇攻击，与祷豆子两人失去了意识。 此时，大批金鱼鬼陆续袭击刀匠们，村子陷入危机。 接到通知的蜜璃出发前往救援村子——。',
    'poster': 'https://image.tmdb.org/t/p/w1280_and_h720_bestv2/vtImSrMdWDsmhXFMs681mkxdGed.jpg',
    'season': 4,
    'seasonId': 61,
    'seasonTitle': '第4季 刀匠村篇',
    'seriesId': 61,
    'seriesTitle': '鬼灭之刃',
    'skipEnding': null,
    'skipIntro': null,
    'subtitles': [],
    'themeColor': 11907002,
    'title': '赫刀',
    'updateAt': '2025-03-22 13:25:52.0 +00:00:00',
    'url': '',
    'watched': false,
  },
  {
    'fileId': '1',
    'mediaCast': actors,
    'airDate': '2023-05-14',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg',
    'downloaded': false,
    'duration': null,
    'episode': 6,
    'ext': 'mp4',
    'favorite': false,
    'fileSize': 0,
    'filename': '鬼灭之刃 - S04E06 - 你不是要成为柱吗！',
    'id': 2350,
    'lastPlayedPosition': null,
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/ecghlDeabR3X3Vv8tXIOeXHQvQe.png',
    'originalTitle': null,
    'overview':
        '炭治郎和他的朋友在奋力抵抗四个分裂的半天狗的攻击。然而，借助禰豆子的血之力，挥舞着燃烧变红的刀，炭治郎成功地同时砍断了其中三只鬼的脖子。炭治郎发现玄弥也斩断了剩下一只鬼的颈部，但是拿着鬼的颈部的玄弥却变了样……',
    'poster': 'https://image.tmdb.org/t/p/w1280_and_h720_bestv2/o0HAhA3zeNsPQPtAnoigJlpCCuk.jpg',
    'season': 4,
    'seasonId': 61,
    'seasonTitle': '第4季 刀匠村篇',
    'seriesId': 61,
    'seriesTitle': '鬼灭之刃',
    'skipEnding': null,
    'skipIntro': null,
    'subtitles': [],
    'themeColor': 11907002,
    'title': '你不是要成为柱吗！',
    'updateAt': '2025-03-22 13:25:52.0 +00:00:00',
    'url': '',
    'watched': false,
  },
  {
    'fileId': '1',
    'mediaCast': actors,
    'airDate': '2023-05-21',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg',
    'downloaded': false,
    'duration': null,
    'episode': 7,
    'ext': 'mp4',
    'favorite': false,
    'fileSize': 0,
    'filename': '鬼灭之刃 - S04E07 - 大坏蛋',
    'id': 2351,
    'lastPlayedPosition': null,
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/ecghlDeabR3X3Vv8tXIOeXHQvQe.png',
    'originalTitle': null,
    'overview':
        '玄弥瞄准了分裂出来的第五只鬼的脖子，然而意外的是，这只鬼的脖子异常坚硬，刀子断了，枪也无效，他被逼入了困境。意识到自己无法亲自斩断鬼的脖子，他将与被认为是本体的第五只鬼对峙的任务交给了炭治郎。炭治郎接受了玄弥的意志，挥动剑向逃窜的鬼劈下——\n\n就算被鬼攻击受到伤害，小铁仍打算救出被玉壶制作的水所囚禁的无一郎。 看着小铁为了自己奋不顾身的模样，无一郎想到炭治郎说过的话，并回想起早已忘记的父亲的样貌。 无一郎得到小铁吹进水中的空气，使出浑身之力施展了霞之呼吸，终于从水中脱困......。',
    'poster': 'https://image.tmdb.org/t/p/w1280_and_h720_bestv2/7jOdHvdpD5oKGsRgixuMCJ5P5vJ.jpg',
    'season': 4,
    'seasonId': 61,
    'seasonTitle': '第4季 刀匠村篇',
    'seriesId': 61,
    'seriesTitle': '鬼灭之刃',
    'skipEnding': null,
    'skipIntro': null,
    'subtitles': [],
    'themeColor': 11907002,
    'title': '大坏蛋',
    'updateAt': '2025-03-22 13:25:52.0 +00:00:00',
    'url': '',
    'watched': false,
  },
  {
    'fileId': '1',
    'mediaCast': actors,
    'airDate': '2023-05-28',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg',
    'downloaded': false,
    'duration': null,
    'episode': 8,
    'ext': 'mp4',
    'favorite': false,
    'fileSize': 0,
    'filename': '鬼灭之刃 - S04E08 - 无一郎的无',
    'id': 2352,
    'lastPlayedPosition': null,
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/ecghlDeabR3X3Vv8tXIOeXHQvQe.png',
    'originalTitle': null,
    'overview': '身受重伤的无一郎，看到受伤的小野，想起了自己过去的回忆，记起了父母的死亡，和自己的双胞胎哥哥，但不久后，鬼出现了，本就支离破碎的家庭，又会经历什么呢',
    'poster': 'https://image.tmdb.org/t/p/w1280_and_h720_bestv2/sM31ISH4HuaSvC9Kf7A76f7SsOa.jpg',
    'season': 4,
    'seasonId': 61,
    'seasonTitle': '第4季 刀匠村篇',
    'seriesId': 61,
    'seriesTitle': '鬼灭之刃',
    'skipEnding': null,
    'skipIntro': null,
    'subtitles': [],
    'themeColor': 11907002,
    'title': '无一郎的无',
    'updateAt': '2025-03-22 13:25:52.0 +00:00:00',
    'url': '',
    'watched': false,
  },
  {
    'fileId': '1',
    'mediaCast': actors,
    'airDate': '2023-06-04',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg',
    'downloaded': false,
    'duration': null,
    'episode': 9,
    'ext': 'mp4',
    'favorite': false,
    'fileSize': 0,
    'filename': '鬼灭之刃 - S04E09 - 霞柱・时透无一郎',
    'id': 2353,
    'lastPlayedPosition': null,
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/ecghlDeabR3X3Vv8tXIOeXHQvQe.png',
    'originalTitle': null,
    'overview': '无一郎与狡猾的玉壶对抗，他露出自己的真面目并发起可怕的攻击。炭治郎等人艰难地与五个头的敌人对抗。',
    'poster': 'https://image.tmdb.org/t/p/w1280_and_h720_bestv2/6EgVImJC0fn0jshgw12NHRf5Rzd.jpg',
    'season': 4,
    'seasonId': 61,
    'seasonTitle': '第4季 刀匠村篇',
    'seriesId': 61,
    'seriesTitle': '鬼灭之刃',
    'skipEnding': null,
    'skipIntro': null,
    'subtitles': [],
    'themeColor': 11907002,
    'title': '霞柱・时透无一郎',
    'updateAt': '2025-03-22 13:25:52.0 +00:00:00',
    'url': '',
    'watched': false,
  },
  {
    'fileId': '1',
    'mediaCast': actors,
    'airDate': '2023-06-11',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg',
    'downloaded': false,
    'duration': null,
    'episode': 10,
    'ext': 'mp4',
    'favorite': false,
    'fileSize': 0,
    'filename': '鬼灭之刃 - S04E10 - 恋柱・甘露寺蜜璃',
    'id': 2315,
    'lastPlayedPosition': null,
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/ecghlDeabR3X3Vv8tXIOeXHQvQe.png',
    'originalTitle': null,
    'overview':
        '炭治郎、祢豆子和玄弥三人在与憎珀天操纵的五条木龙的战斗中陷入了困境。面对使用喜怒哀乐四位鬼的力量的木龙们的防守，炭治郎被木龙吞噬。就在绝境之际，蜜璃赶到并救出了炭治郎。然后，为了救出被捕的祢󠄀豆子和玄弥，他们决意面对憎珀天！',
    'poster': 'https://image.tmdb.org/t/p/w1280_and_h720_bestv2/iKD90AUxGHcLHGvbuSKfqq76rbE.jpg',
    'season': 4,
    'seasonId': 61,
    'seasonTitle': '第4季 刀匠村篇',
    'seriesId': 61,
    'seriesTitle': '鬼灭之刃',
    'skipEnding': null,
    'skipIntro': null,
    'subtitles': [],
    'themeColor': 11907002,
    'title': '恋柱・甘露寺蜜璃',
    'updateAt': '2025-03-22 13:25:52.0 +00:00:00',
    'url': '',
    'watched': false,
  },
  {
    'fileId': '1',
    'mediaCast': actors,
    'airDate': '2023-06-18',
    'backdrop': 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg',
    'downloaded': false,
    'duration': null,
    'episode': 11,
    'ext': 'mp4',
    'favorite': false,
    'fileSize': 0,
    'filename': '鬼灭之刃 - S04E11 - 连系的羁绊 黎明・拂晓',
    'id': 2316,
    'lastPlayedPosition': null,
    'lastPlayedTime': null,
    'logo': 'https://image.tmdb.org/t/p/w500/ecghlDeabR3X3Vv8tXIOeXHQvQe.png',
    'originalTitle': null,
    'overview':
        '趁着恋柱挡住憎珀天的时候，炭治郎、祢󠄀豆子以及玄弥前往追赶半天狗的真身。他们三个找到了藏着半天狗的木球，并合力将球击破，然而里面已经只剩下空壳。炭治郎等人继续追赶再次逃走的半天狗，玄弥对四处逃窜的半天狗感到不耐烦，便拔起树干扔了过去，祢󠄀豆子也扑了上去......！',
    'poster': 'https://image.tmdb.org/t/p/w1280_and_h720_bestv2/kFvPNnB8215j0xudEtFXa7oJ8F6.jpg',
    'season': 4,
    'seasonId': 61,
    'seasonTitle': '第4季 刀匠村篇',
    'seriesId': 61,
    'seriesTitle': '鬼灭之刃',
    'skipEnding': null,
    'skipIntro': null,
    'subtitles': [],
    'themeColor': 11907002,
    'title': '连系的羁绊 黎明・拂晓',
    'updateAt': '2025-03-22 13:25:52.0 +00:00:00',
    'url': '',
    'watched': false,
  },
];

const studios = [
  {
    'country': 'JP',
    'id': 3,
    'logo': 'https://image.tmdb.org/t/p/h50/4x4GsmRmSLLL0RVNKsoqAVH43tz.png',
    'name': 'Fuji TV',
    'scrapper': {'id': '1', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 4,
    'logo': 'https://image.tmdb.org/t/p/h50/9rNqtDYAnD6yTOutvHI3synSEs2.png',
    'name': 'Gunma TV',
    'scrapper': {'id': '343', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 5,
    'logo': 'https://image.tmdb.org/t/p/h50/hSdroyVthq3CynxTIIY7lnS8w1.png',
    'name': 'Tokyo MX',
    'scrapper': {'id': '614', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 6,
    'logo': 'https://image.tmdb.org/t/p/h50/JQ5bx6n7Qmdmyqz6sqjo5Fz2iR.png',
    'name': 'BS11',
    'scrapper': {'id': '861', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 7,
    'logo': 'https://image.tmdb.org/t/p/h50/pX3gDCsG8WcQvQbCNJ37t5w0HyG.png',
    'name': 'Tokai Television Broadcasting',
    'scrapper': {'id': '879', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 8,
    'logo': 'https://image.tmdb.org/t/p/h50/1J33ZvSff1VOEt3aC8CyKmj9GEy.png',
    'name': 'Kansai TV',
    'scrapper': {'id': '1163', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 9,
    'logo': 'https://image.tmdb.org/t/p/h50/2v82HpzoKRveJEJcGHkeTcktMRM.png',
    'name': 'Tochigi TV',
    'scrapper': {'id': '2478', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 10,
    'logo': 'https://image.tmdb.org/t/p/h50/sces9gh6ih1DaD54WXvqHeLMScE.png',
    'name': 'Fukui TV',
    'scrapper': {'id': '3535', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 11,
    'logo': 'https://image.tmdb.org/t/p/h50/vkOmMDoyA8Jj8gDJOyP6CjD06Kj.png',
    'name': 'Hokkaido Cultural Broadcasting',
    'scrapper': {'id': '3721', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 12,
    'logo': 'https://image.tmdb.org/t/p/h50/y1F9WoEjz7MhzjN56im3tVKTd1r.png',
    'name': 'Iwate Menkoi Television',
    'scrapper': {'id': '4799', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 13,
    'logo': 'https://image.tmdb.org/t/p/h50/9dD3buakf1nS6XQVBwEtm50izs4.png',
    'name': 'TOS',
    'scrapper': {'id': '4825', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 14,
    'logo': 'https://image.tmdb.org/t/p/h50/qHGklsa90XMreAdYm7AZl6eeaCL.png',
    'name': 'Sendai Television',
    'scrapper': {'id': '4829', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 15,
    'logo': 'https://image.tmdb.org/t/p/h50/pRhoUkllLEe3U9341NUCeKdQ7to.png',
    'name': 'SAGA TV',
    'scrapper': {'id': '4839', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 16,
    'logo': 'https://image.tmdb.org/t/p/h50/7QZ9b8bIpNUU5AjdaW6BXcMziY6.png',
    'name': 'Ishikawa TV',
    'scrapper': {'id': '4841', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 17,
    'logo': 'https://image.tmdb.org/t/p/h50/thh0SqE1oh7oOH08ISphk6cRghq.png',
    'name': 'TNC',
    'scrapper': {'id': '4850', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 18,
    'logo': 'https://image.tmdb.org/t/p/h50/wd94E8WjZwEbu1PLxhNNH0Ny3VT.png',
    'name': 'OHK',
    'scrapper': {'id': '4851', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 19,
    'logo': 'https://image.tmdb.org/t/p/h50/vRWtsyWIcIrtw0PXbCbjC4xvXtw.png',
    'name': 'Kochi Sun Sun Broadcasting',
    'scrapper': {'id': '4855', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 20,
    'logo': 'https://image.tmdb.org/t/p/h50/6hrEhIW5lIUKeX78BNTzMQ0e8aK.png',
    'name': 'Television Shin Hiroshima System',
    'scrapper': {'id': '4970', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 21,
    'logo': 'https://image.tmdb.org/t/p/h50/832SJcpnozaNWKto6hPSpYvDYQU.png',
    'name': 'TV Shizuoka',
    'scrapper': {'id': '5644', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 22,
    'logo': 'https://image.tmdb.org/t/p/h50/gxpzF98cV1DHpXzJmXf2Ew6sQvV.png',
    'name': 'UMK TV Miyazaki',
    'scrapper': {'id': '6156', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 23,
    'logo': 'https://image.tmdb.org/t/p/h50/fjenNun3vCLtnHHsTpAgVYkubMl.png',
    'name': 'NST',
    'scrapper': {'id': '6209', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 24,
    'logo': 'https://image.tmdb.org/t/p/h50/kCNJcIxnOXI4fkc8oZLOk1BZb0o.png',
    'name': 'NBS',
    'scrapper': {'id': '6210', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 25,
    'logo': 'https://image.tmdb.org/t/p/h50/mFM7fx4yt3FOa6leUbBbd8iGZIi.png',
    'name': 'Sakuranbo TV',
    'scrapper': {'id': '6211', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 26,
    'logo': 'https://image.tmdb.org/t/p/h50/eAaH52WuIH4XNlqYSonXZRPRnGE.png',
    'name': 'TSK',
    'scrapper': {'id': '6212', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 27,
    'logo': 'https://image.tmdb.org/t/p/h50/np5gbKJvysVLnJKg8g1OxhiA6Qa.png',
    'name': 'Ehime Broadcasting',
    'scrapper': {'id': '6213', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 28,
    'logo': 'https://image.tmdb.org/t/p/h50/fF4u5E7SBK4qOoIUOVmr5FbYk2g.png',
    'name': 'KTS',
    'scrapper': {'id': '6214', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 29,
    'logo': 'https://image.tmdb.org/t/p/h50/rCdk5TWd3RPKTZU1zlhDCEFuzsI.png',
    'name': 'Fukushima TV',
    'scrapper': {'id': '6666', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 30,
    'logo': 'https://image.tmdb.org/t/p/h50/7OAJi6aS9zQWwP64jqxRllBvYKR.png',
    'name': 'NIB',
    'scrapper': {'id': '6670', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 31,
    'logo': 'https://image.tmdb.org/t/p/h50/hNbCO6N6F4o09DCGAoz7g0G2E9F.png',
    'name': 'AKT',
    'scrapper': {'id': '6819', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 32,
    'logo': 'https://image.tmdb.org/t/p/h50/mkTZDdapxuLVS4gzSCwD01DFkbw.png',
    'name': 'Toyama Television',
    'scrapper': {'id': '6821', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 33,
    'logo': 'https://image.tmdb.org/t/p/h50/lquU1iSzXNKMWohDVIE91pxDzhE.png',
    'name': 'TV Kumamoto',
    'scrapper': {'id': '6822', 'type': 'tmdb'},
  },
  {
    'country': 'JP',
    'id': 34,
    'logo': 'https://image.tmdb.org/t/p/h50/UQS8TXqK0b367KX6Vw0aOfMB.png',
    'name': 'Okinawa Television Broadcasting',
    'scrapper': {'id': '6823', 'type': 'tmdb'},
  },
];

const genres = [
  {
    'id': 5,
    'name': '动画',
    'scrapper': {'id': '16', 'type': 'tmdb'},
  },
  {
    'id': 6,
    'name': '动作冒险',
    'scrapper': {'id': '10759', 'type': 'tmdb'},
  },
  {
    'id': 7,
    'name': 'Sci-Fi & Fantasy',
    'scrapper': {'id': '10765', 'type': 'tmdb'},
  },
];

const keywords = [
  {
    'id': 8,
    'name': 'sibling relationship',
    'scrapper': {'id': '380', 'type': 'tmdb'},
  },
  {
    'id': 9,
    'name': 'swordplay',
    'scrapper': {'id': '1400', 'type': 'tmdb'},
  },
  {
    'id': 10,
    'name': 'magic',
    'scrapper': {'id': '2343', 'type': 'tmdb'},
  },
  {
    'id': 11,
    'name': 'supernatural',
    'scrapper': {'id': '6152', 'type': 'tmdb'},
  },
  {
    'id': 12,
    'name': 'undead',
    'scrapper': {'id': '10327', 'type': 'tmdb'},
  },
  {
    'id': 13,
    'name': 'tragedy',
    'scrapper': {'id': '10614', 'type': 'tmdb'},
  },
  {
    'id': 14,
    'name': 'coming of age',
    'scrapper': {'id': '10683', 'type': 'tmdb'},
  },
  {
    'id': 15,
    'name': 'based on manga',
    'scrapper': {'id': '13141', 'type': 'tmdb'},
  },
  {
    'id': 16,
    'name': 'demon',
    'scrapper': {'id': '15001', 'type': 'tmdb'},
  },
  {
    'id': 17,
    'name': 'mutilation',
    'scrapper': {'id': '157512', 'type': 'tmdb'},
  },
  {
    'id': 18,
    'name': 'dark fantasy',
    'scrapper': {'id': '177895', 'type': 'tmdb'},
  },
  {
    'id': 19,
    'name': 'anachronism',
    'scrapper': {'id': '201950', 'type': 'tmdb'},
  },
  {
    'id': 20,
    'name': 'shounen',
    'scrapper': {'id': '207826', 'type': 'tmdb'},
  },
  {
    'id': 21,
    'name': 'anime',
    'scrapper': {'id': '210024', 'type': 'tmdb'},
  },
  {
    'id': 22,
    'name': 'time skip',
    'scrapper': {'id': '244663', 'type': 'tmdb'},
  },
  {
    'id': 25,
    'name': 'lacrimation',
    'scrapper': {'id': '317156', 'type': 'tmdb'},
  },
  {
    'id': 41,
    'name': 'demon hunter',
    'scrapper': {'id': '186425', 'type': 'tmdb'},
  },
  {
    'id': 71,
    'name': 'taisho period',
    'scrapper': {'id': '343025', 'type': 'tmdb'},
  },
  {
    'id': 137,
    'name': 'shocking',
    'scrapper': {'id': '200234', 'type': 'tmdb'},
  },
  {
    'id': 153,
    'name': 'sword',
    'scrapper': {'id': '1938', 'type': 'tmdb'},
  },
  {
    'id': 154,
    'name': 'training',
    'scrapper': {'id': '4613', 'type': 'tmdb'},
  },
  {
    'id': 155,
    'name': 'breathing',
    'scrapper': {'id': '209947', 'type': 'tmdb'},
  },
  {
    'id': 156,
    'name': 'demon slayer',
    'scrapper': {'id': '279745', 'type': 'tmdb'},
  },
];
