name: openlist
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  api:
    path: ../api
  dio: ^5.7.0
  shared_preferences: ^2.5.0
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ghosten.openlist
        pluginClass: OpenlistPlugin
      web:
        pluginClass: OpenlistWeb
        fileName: src/openlist_web.dart
