name: Bug report
description: |
  Please report any bugs you encounter here
  请通过这里反馈遇到的 Bug 类问题
labels: [ bug ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you very much for your feedback, which will help me improve this project. Before that, please fill in the following form as detailed as possible to facilitate better positioning of the problem.
        非常感谢您的问题反馈，帮助我完善此项目，在此之前，请尽可能详细填写以下表单，方便更好的定位问题。

  - type: input
    attributes:
      label: Version / 版本
      placeholder: |
        Please provide the specific version number of this repository, such as 1.0.0
        请提供本项目具体版本号如 1.0.0
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Running platform / 运行平台
      description: |
        What platform are you running this repository on?
        您在什么平台上运行的该项目？
      options:
        - Android Phone / 安卓手机
        - Android Pad / 安卓平板
        - Android TV / 安卓电视
    validations:
      required: true

  - type: input
    attributes:
      label: Device model / 设备型号
      placeholder: |
        Such as Redmi K70
        比如Redmi K70
      description: |
        The device model you are using
        您使用的设备型号

  - type: input
    attributes:
      label: Android Version / 安卓版本
      placeholder: Such as Android13 / 比如Android13
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem description / 问题描述
      description: |
        Please describe the problem you encountered in detail. If it is a UI-related problem, it would be best if you can provide screenshots.
        请详细描述您遇到的问题，如果是UI相关问题，最好能提供截图
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem recurrence / 问题复现
      description: |
        Please provide steps to reproduce the problem to help locate the problem.
        If the problem is related to the player, this is a required field. You need to explain the source of the media file, encoding information, etc., and whether the problem can be stably reproduced.
        请提供复现该问题的步骤，方便定位问题所在。
        如果是播放器相关问题，此为必填项。需说明媒体文件的来源，编码信息等，以及能否稳定复现。
      placeholder: |
        1.
        2.
        3.
        
  - type: textarea
    attributes:
      label: Log / 日志
      description: |
        There is a log function in the settings. You can copy the error log by long pressing it, or upload a screenshot directly.
        设置中有日志功能，长按报错的日志可以进行复制，也可直接上传截图
      placeholder: |
        1.
        2.
        3.
  
