name: Deploy to GitHub Pages

on:
  release:
    types: [ "published" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge main -> gh-pages
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: gh-pages
          github_token: ${{ secrets.TOKEN }}

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.32.8'

      - run: flutter pub get

      - name: Build
        run: |
          flutter build web --wasm \
          --target=lib/main_demo.dart \
          --base-href=/Ghosten-Player/ \
          --dart-define=BUILD_DATE=$(date "+%F")

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/web/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
