name: Deploy to GitHub Pages

on:
  push:
    branches: [ "gh-pages" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.27.4'

      - run: flutter pub get

      - name: Build
        run: |
          flutter build web \
          --base-href=/Ghosten-Player/
          --dart-define=BUILD_DATE=$(date "+%F")

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
