name: Issue Lack of Information

on:
  issues:
    types: [labeled]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'lack of information'
    steps:
      - name: Create comment
        uses: actions-cool/issues-helper@v3.6.0
        with:
          actions: 'create-comment'
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, please fill in the issue template and describe the problem in detail. Issues labeled by `lack of information` will be closed if no activities in 3 days.
