name: No Response

on:
  schedule:
    - cron: "0 0 */1 * *"
  workflow_dispatch:

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Without additional information, I'm unfortunately not sure how to
            resolve this issue. I'm therefore reluctantly going to close this
            bug for now.

            If you can offer the additional information, reopen this issue.

            Thanks for your contribution.
          inactive-day: 7
          labels: "waiting for customer response"
